name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:postgres@localhost/ci_test"
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: webpacker
        run: |
          yarn install --check-files
          yarn upgrade
          bundle exec rails webpacker:compile
      - name: Rspec
        run: |
          bundle exec rails db:create
          bundle exec rails db:seed
          bundle exec rspec
      - name: Archive screenshot
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: Screenshot of the test
          path: tmp/screenshots
