name: Test

on: [push]

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup docker
        shell: bash
        run: |
          docker-compose build
          docker-compose run web rails db:create
          docker-compose run web rails db:migrate
          docker-compose run web rails db:seed
      - name: RSpec
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          RAILS_ENV: test
        run: |
          docker-compose run web bundle exec rspec
      - name: Jest
        run: docker-compose run web yarn test
