name: Test

on: [push]

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup docker
        shell: bash
        run: |
          docker-compose build
          docker-compose run web rails db:create
        env:
          RAILS_ENV: test
      - name: webpacker
        run: |
          docker-compose run web yarn install --check-files
          docker-compose run web yarn upgrade
          docker-compose run web bundle exec rails webpacker:compile
      - name: Rspec
        run: |
          docker-compose run web bundle exec rspec
        env:
          RAILS_ENV: test
